"""init db

Revision ID: 1663292d0bd8
Revises: 
Create Date: 2022-11-09 15:08:10.017827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1663292d0bd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_channel_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=254), nullable=True),
    sa.Column('value', sa.String(length=5000), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_channel_setting')
    # ### end Alembic commands ###
