"""add: channel_params table

Revision ID: 3f54250e3fca
Revises: 1663292d0bd8
Create Date: 2023-02-09 12:36:18.086948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f54250e3fca'
down_revision = '1663292d0bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sys_channel_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance', sa.String(length=254), nullable=True),
    sa.Column('params', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sys_channel_params')
    # ### end Alembic commands ###
