#!/usr/bin/python3
# coding=utf-8
import sys
import json
import random

def iosdiagJoinData(raw):
    if raw.startswith('fail'):
        data = {"status":"fail"}
    elif 'summary' not in raw:
        data = {"status":"success","IO timeout":"false"}
    else:
        data = {"status":"success","IO timeout":"true","stat":[],"seq":[]}
        for s in raw.split('\n'):
            obj = json.loads(s)
            if "percent" in str(obj):
                data['stat'] = obj['summary']
            else:
                data["seq"] = obj['summary']
    s = json.dumps(data, indent=4)
    print(s)

if __name__ == "__main__":
    iosdiagJoinData(sys.argv[1])
