#!/usr/bin/python3
# coding=utf-8
import json
import sys

###############################################################################
##  如前端入参是这个：
##  {
##    "源虚拟机私网IP":"192.168.1.101",
##    "目标虚拟机私网IP":"192.168.1.102",
##    "追踪包数":"100",
##    "间隔毫秒数":"10",
##    "报文协议":"ICMP"
##  }
##  解析参数方法：
##  sysak pingtrace -s -t 6
##  -t 6 来自 “追踪包数” * "间隔毫秒数” / 1000 + 5
##  本命令运行在“目标虚拟机私网ip”
##  
##  sysak pingtrace_raw -c 192.168.1.102 -t 2 -i 10000 -C 100 -o log
##  -c 192.168.1.102 来自 “目标虚拟机私网ip”
##  -t 2 来自 “追踪包数” * "间隔毫秒数” / 1000 + 1 
##  -i 10000 来自 “间隔毫秒数”* 1000
##  -C 100 来自 “追踪包数”
##  本命令运行在“源虚拟机私网ip”
###############################################################################

args = json.loads(sys.argv[1])
result = {}
result['commands'] = []

cmd0_arg = int(int(args["追踪包数"]) * int(args["间隔毫秒数"]) / 1000) + 5
cmd0 = {}
cmd0['instance'] = args["源实例IP"]
cmd0['cmd'] = "sysak pingtrace -s -t "+str(cmd0_arg)+" > /dev/null 2>&1 &"

cmd1 = {}
cmd1['instance'] = args["目标实例IP"]
cmd1_arg_c = args["目标实例IP"]
cmd1_arg_t = str(cmd0_arg - 4)
cmd1_arg_i = str(int(args["间隔毫秒数"]) * 1000)
cmd1_arg_C = str(args["追踪包数"])
cmd1['cmd'] = "sysak pingtrace -c "+cmd1_arg_c+" -t "+cmd1_arg_t+" -i "+cmd1_arg_i+" -C "+cmd1_arg_C+" > /tmp/pingtrace.log && cat /tmp/pingtrace.log"

result['commands'].append(cmd0)
result['commands'].append(cmd1)

data = json.dumps(result)
print(data)
