#!/usr/bin/python3
# coding=utf-8
import sys
import os
import json
import random
import collections

class schedmoni(object):
	def __init__(self, f):
		super(schedmoni, self).__init__()
		self._file = f

	def proc_data(self):
		tmp = self._file.readlines()
		print(tmp);

if __name__ == "__main__":
	str1 = sys.argv[1]
	str2 = str1.replace('\n', "")
	str3 = str2.replace('\t', "")
	print(str3)
