#!/usr/bin/python3
# coding=utf-8

import json
import sys
import os
import time
###################################################################
## 如前端输入
## {
##	"instance":"192.168.1.101",
##	"thresh":"10000",
##	"diag_time":"10",
## }
## '{"instance":"192.168.1.101", "diag_time":20, "thresh":50}'
## 解析参数方法:
## sysak schedmoni -j -s 20 50
##  50 门限, 捕获延迟超过50ms的事件
##  -s 20 诊断时间20秒
##
######################################################################
class Param(dict):
    def __missing__(self,key):
        sys.stderr.write("入参检查失败，没有检查到入参'%s'"%key)
        exit(1)

args = Param(json.loads(sys.argv[1]))

result = {}
result['commands'] = []

cmd0 = {}
cmd0['instance'] = args["instance"]
arg_time = args["diag_time"]
if arg_time:
	arg_time = '-s ' + str(arg_time)
arg_thresh = args["thresh"]

dump_log_cmd = "cat /var/log/sysak/schedmoni/schedmoni.json;"
schedmoni_cmd = "sysak schedmoni -j "+str(arg_time)+" "+str(arg_thresh)+" > /dev/null"
cmd0['cmd'] = schedmoni_cmd+" && "+dump_log_cmd

result['commands'].append(cmd0)

data = json.dumps(result)
print(data)
