# sysom_server config
sysom_global:
  path:
    root_path: &global_root_path /usr/local/sysom

# Unified configuration of Server
sysom_server:
  path:
    root_path:
      !concat &sysom_server_root_path [
        *global_root_path,
        "/server/target/sysom_server",
      ]
  db:
    redis:
      host: localhost
      port: 6379
      username:
      password:
    mysql:
      host: localhost
      port: 3306
      user: sysom
      password: sysom_admin
      database: sysom
  jwt:
    # JWT token secret key
    SECRET_KEY: "django-insecure-^d8b9di9w&-mmsbpt@)o#e+2^z+^m4nhf+z8304%9@8y#ko46l"
    # JWT token expire time (2 days)
    TOKEN_EXPIRE: 172800
  cec:
    protocol: redis
    # 各个微服务对外提供服务的主题统一定义在这
    topics:
      # 用于分发插件系统相关事件的主题
      SYSOM_CEC_PLUGIN_TOPIC: SYSOM_CEC_PLUGIN_TOPIC
      # 通道模块用于对外开放，投递操作的主题
      SYSOM_CEC_CHANNEL_TOPIC: SYSOM_CEC_CHANNEL_TOPIC
      # 通道模块用于投递执行结果的主题
      SYSOM_CEC_CHANNEL_RESULT_TOPIC: SYSOM_CEC_CHANNEL_RESULT_TOPIC
      # 警告通知事件投递主题
      SYSOM_CEC_ALARM_TOPIC: SYSOM_CEC_ALARM_TOPIC

      # Host
      SYSOM_CEC_API_HOST_TOPIC: SYSOM_CEC_API_HOST_TOPIC

    special_param:
      comm:
        cec_default_max_len: 1000
      admin:
      producer:
        cec_auto_mk_topic: true
      consumer:
  logger:
    format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <cyan>{file.path}</cyan>:<cyan>{line}</cyan> | {message}"

# Unified configuration of Web
sysom_web:
  path:
    root_path: !concat [*global_root_path, "/server/target/sysom_web"]

# Unified configuration of Node
sysom_node:
  path:
    root_path: !concat &sysom_node_root_path [*global_root_path, "/node"]
  # 与节点交互命令超时时间，单位为 ms
  timeout: 60000
  envs:
    NODE_HOME: *sysom_node_root_path
    APP_HOME: *global_root_path
    SERVER_HOME: !concat [*global_root_path, "/server"]
    SERVER_LOCAL_IP: 127.0.0.1
    SERVER_PUBLIC_IP: 127.0.0.1
    SERVER_PORT: 80
