# Generated by Django 3.2.8 on 2022-11-28 06:51

from django.db import migrations, models
import django.db.models.deletion
import lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='更新时间')),
                ('calltrace', models.CharField(max_length=256)),
                ('crashkey', models.CharField(max_length=256)),
                ('solution', models.TextField()),
            ],
            options={
                'db_table': 'issue',
            },
        ),
        migrations.CreateModel(
            name='Panic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ip', models.CharField(max_length=64, null=True)),
                ('hostname', models.CharField(max_length=128)),
                ('vertype', models.IntegerField()),
                ('status', models.IntegerField()),
                ('core_time', models.DateTimeField()),
                ('vmcore_file', models.CharField(max_length=256)),
                ('dmesg_file', models.CharField(max_length=256)),
                ('dmesg', models.TextField()),
                ('title', models.CharField(max_length=128)),
                ('ver', models.CharField(max_length=128)),
                ('rip', models.CharField(max_length=64)),
                ('func_name', models.CharField(max_length=64)),
                ('comm', models.CharField(max_length=64)),
                ('calltrace', models.CharField(max_length=256)),
                ('crashkey', models.CharField(max_length=256)),
                ('modules', models.CharField(max_length=512)),
                ('upload_time', models.IntegerField()),
                ('issue_id', models.IntegerField()),
                ('panic_type', models.CharField(max_length=64)),
                ('panic_class', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'panic',
            },
        ),
        migrations.CreateModel(
            name='VmcoreConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('server_host', models.CharField(max_length=256)),
                ('mount_point', models.CharField(max_length=256)),
                ('days', models.IntegerField()),
            ],
            options={
                'db_table': 'vmcore_config',
            },
        ),
        migrations.CreateModel(
            name='Calltrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='更新时间')),
                ('name', models.CharField(max_length=128)),
                ('line', models.CharField(max_length=128)),
                ('idx', models.IntegerField()),
                ('vmcore', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='panic_call_trace', to='vmcore.panic', to_field='name')),
            ],
            options={
                'db_table': 'call_trace',
            },
        ),
    ]
