#!/usr/bin/python3
# coding=utf-8
import os
import sys
import json
import random

def oomcheck_result(raw):
    result = {}
    result = {"CommandResult":{"data":[{"key":"","value":raw}]}}
    print(json.dumps(result))

def extract_params():
    path, res, task_id = sys.argv[1], "", sys.argv[2]
    with open(path, 'r') as tmp:
        for line in tmp.readlines():
            res = res + "\r" + line
    return res, task_id

if __name__ == "__main__":
    res, _ = extract_params()
    oomcheck_result(res)
