# Generated by Django 3.2.16 on 2023-02-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_login',
            field=models.BooleanField(default=True),
        ),
    ]
