vars:
  SYSAK_DOWNLOAD_URL: &SYSAK_DOWNLOAD_URL https://mirrors.openanolis.cn/sysak/packages/
  SYSAK_VERSION: &SYSAK_VERSION 1.3.0-2
  SERVICE_NAME: &SERVICE_NAME sysom_diagnosis
  SERVICE_CONSUMER_GROUP:
    &SERVICE_CONSUMER_GROUP !concat [*SERVICE_NAME, "_consumer_group"]

sysom_server:
  cec:
    consumer_group: *SERVICE_CONSUMER_GROUP
  channel_job:
    target_topic: SYSOM_CEC_CHANNEL_TOPIC
    listen_topic: SYSOM_CEC_CHANNEL_DIAGNOSIS_TOPIC
    consumer_group: *SERVICE_CONSUMER_GROUP

sysom_service:
  service_name: *SERVICE_NAME
  service_dir: *SERVICE_NAME

# 节点测配置
sysom_node:
  version: 2.1
  # 节点分发配置
  delivery:
    from_dir: scripts
    to_dir: node
    files:
      comm: &code_delivery_files_comm
        - local: node_init.sh
          remote:
        - local: node_clear.sh
          remote:
        - local: node_update.sh
          remote:
      amd64: &node_delivery_files_amd64
        - *code_delivery_files_comm
        - local: node_exporter-1.5.0.linux-amd64.tar.gz
          local: !concat ["sysak-", *SYSAK_VERSION, ".x86_64.rpm"]
          remote:
            !concat [
              *SYSAK_DOWNLOAD_URL,
              "sysak-",
              *SYSAK_VERSION,
              ".x86_64.rpm",
            ]
      arm64: *node_delivery_files_amd64
      x86_64: *node_delivery_files_amd64
  scripts:
    prepare: node_prepare.sh
    init: node_init.sh
    clear: node_clear.sh
    update: node_update.sh
