# Generated by Django 3.2.16 on 2022-12-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostmodel',
            name='host_info',
            field=models.TextField(default='', verbose_name='主机信息'),
        ),
    ]
