# Generated by Django 3.2.16 on 2022-12-27 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_alter_hostmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostmodel',
            name='ip',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.validate_ipv46_address]),
        ),
        migrations.AlterField(
            model_name='hostmodel',
            name='port',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(65535), django.core.validators.MinValueValidator(0)]),
        ),
    ]
