{
 "title": "migration-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_cpu_seconds_total, instance)"
    }
   },
   {
    "name": "migration_offset",
    "query": "select concat(timestampdiff(SECOND, created_at, now()), 's') as offset from mig_implementation where ip=left('$instance', locate(':', '$instance') - 1)"
   }
  ]
 },
 "panels": [
  { "title": "资源总额", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>迁移前后资源总额对比</h3>\n</div>"
   }
  },
  {
   "title": "原始内核版本",
   "type": "stat",
   "description": "内核版本（Kernel Version）：",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\"} offset $migration_offset",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 3 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前内核版本",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "原始内存可用总量",
   "type": "stat",
   "description": "内存可用总量（Memory Total）：除去预留内存和内核使用的内存，用户总的可用内存",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"} offset $migration_offset",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 5 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前内存可用总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "原始大页内存总量",
   "type": "stat",
   "description": "大页内存总量（Huge Page Memory Total）",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=\"$instance\"} offset $migration_offset",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 7 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前大页内存总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_HugePages_Total{instance=\"$instance\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "原始磁盘可用空间总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=\"$instance\",device!~'(rootfs|tmpfs)'} offset $migration_offset) by (device))",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 9 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前磁盘可用空间总量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=\"$instance\",device!~'(rootfs|tmpfs)'}) by (device))",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "title": "原始磁盘个数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg(node_filesystem_avail_bytes{device!~'(rootfs|tmpfs)'} offset $migration_offset) by (device))",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 11 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前磁盘个数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg(node_filesystem_avail_bytes{device!~'(rootfs|tmpfs)'}) by (device))",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "title": "原始网卡数量",
   "type": "stat",
   "description": "不包括lo",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_network_info{device!~\"lo\"} offset $migration_offset)",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 13 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前网卡数量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_network_info{device!~\"lo\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "title": "原始启用网卡数量",
   "type": "stat",
   "description": "不包括lo",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_network_info{device!~\"lo\", operstate=\"up\"} offset $migration_offset)",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 15 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>→</h3>\n</div>"
   }
  },
  {
   "title": "当前启用网卡数量",
   "type": "stat",
   "gridPos": { "h": 2, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_network_info{device!~\"lo\", operstate=\"up\"})",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>迁移过程资源总额变化监控</h3>\n</div>"
   }
  },
  {
   "title": "可用内存",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$instance\"}",
     "legendFormat": "total"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$instance\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "可用磁盘空间",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size_bytes{instance=\"$instance\",device!~'(rootfs|tmpfs)'}) by (device))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg(node_filesystem_avail_bytes{instance=\"$instance\",device!~'(rootfs|tmpfs)'}) by (device))",
     "legendFormat": "avaliable"
    }
   ]
  },
  { "title": "资源监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>CPU</h3>\n</div>"
   }
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 利用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 3, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "今日"
    },
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval] offset 1d)) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "昨日"
    }
   ]
  },
  {
   "title": "CPU 利用率两日差值",
   "type": "timeseries",
   "description": "abs( 本日CPU利用率 - 昨日同时刻CPU利用率 )",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "abs(((1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100) - ((1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval] offset 1d)) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100))",
     "legendFormat": "CPU 利用率差值"
    }
   ]
  },
  {
   "title": "实时 CPU 利用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU 利用率两日分布",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "今日"
    },
    {
     "expr": "(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval] offset 1d)) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100",
     "legendFormat": "昨日"
    }
   ]
  },
  {
   "title": "CPU利用率波动",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "stddev_over_time(((1 - sum(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$instance\"}[$__rate_interval])) / count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu))) * 100)[5m:$__rate_interval])",
     "legendFormat": "标准差"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 52 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>Memory</h3>\n</div>"
   }
  },
  {
   "title": "实时内存使用率",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"} )) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "内存使用率（Memory Usage）",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"} )) * 100",
     "legendFormat": "Memory utilization rate"
    }
   ]
  },
  {
   "title": "内存使用率波动（Memory Usage Rate Fluctuation）",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "stddev_over_time((((node_memory_MemTotal_bytes{instance=\"$instance\"} - node_memory_MemFree_bytes{instance=\"$instance\"}) / (node_memory_MemTotal_bytes{instance=\"$instance\"} )) * 100)[2m:$__rate_interval])",
     "legendFormat": "标准差(stddev)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 65 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>Disk</h3>\n</div>"
   }
  },
  {
   "title": "磁盘空间总额",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"$instance\",fstype!=\"rootfs\", device=\"tmpfs\"} ",
     "legendFormat": "{{device}} => {{mountpoint}}"
    },
    {
     "expr": "avg(node_filesystem_size_bytes{instance=\"$instance\",fstype!=\"rootfs\", device!=\"tmpfs\"}) by (device) ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "磁盘空间使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (((avg(node_filesystem_avail_bytes{instance=\"$instance\",device!~'rootfs'}) by (device)) * 100) / (avg(node_filesystem_size_bytes{instance=\"$instance\",device!~'rootfs'}) by (device)))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk Read IOps",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Write completed"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "timeseries",
   "description": "The number of bytes read from or written to the device per second",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "-rate(node_disk_read_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Written bytes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 86 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>Network</h3>\n</div>"
   }
  },
  {
   "title": "实时接收速率",
   "type": "stat",
   "description": "所有网卡接收速率之和",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "网络流量监控",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 3, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "接收速率"
    },
    {
     "expr": "-sum(rate(node_network_transmit_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "发送速率"
    }
   ]
  },
  {
   "title": "网络流量波动监测",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "stddev_over_time((sum(rate(node_network_receive_bytes_total{instance=\"$instance\"}[$__rate_interval])))[2m:$__rate_interval])",
     "legendFormat": "接收速率标准差"
    },
    {
     "expr": "-stddev_over_time((sum(rate(node_network_transmit_bytes_total{instance=\"$instance\"}[$__rate_interval])))[2m:$__rate_interval])",
     "legendFormat": "发送速率标准差"
    }
   ]
  },
  {
   "title": "实时发送速率",
   "type": "stat",
   "description": "所有网卡发送速率之和",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 100 },
   "options": {
    "content": "<div style=\"width: 100%; height: 100%; display: flex; align-items: center; justify-content: center;\">\n<h3>System Load</h3>\n</div>"
   }
  },
  {
   "title": "实时系统负载（1分钟）",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "系统负载",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100",
     "legendFormat": "1分钟内负载（Load1）"
    },
    {
     "expr": "avg(node_load5{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100",
     "legendFormat": "5分钟内负载（Load5）"
    },
    {
     "expr": "avg(node_load15{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100",
     "legendFormat": "15分钟内负载（Load15）"
    }
   ]
  },
  {
   "title": "系统负载波动（Load1）",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "stddev_over_time((avg(node_load1{instance=\"$instance\"}) /  count(count(node_cpu_seconds_total{instance=\"$instance\"}) by (cpu)) * 100)[2m:$__rate_interval])",
     "legendFormat": "标准差"
    }
   ]
  }
 ]
}