{
 "title": "sysom-netinfo",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "LINUXHOST",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  { "title": "Summay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "SELECT last(\"name\") FROM \"os_host_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Operating System Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "SELECT last(\"os_kernel\") FROM \"os_host_release\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "SELECT last(\"cpus\") FROM \"lscpu\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "CPU health",
   "type": "stat",
   "description": "CPU health，should not lower than 60%",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "select floor(mean(idle)) from cpu_total where  (\"host\" =~ /^$LINUXHOST$/) and time > now() - 10m"
    }
   ]
  },
  {
   "title": "disk busy rate(%)",
   "type": "stat",
   "description": "disk busy rate. the lower the better",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "select max(busy) from disks where (\"host\" =~ /^$LINUXHOST$/) and time > now() - 10m"
    }
   ]
  },
  {
   "title": "net retrans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "select sum(total) as retrans from net_retrans where (\"host\" =~ /^$LINUXHOST$/) and time > now() - 1h"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "last",
     "query": "SELECT last(\"model\") FROM \"identity\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "mem summary",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "select last(\"MemTotal\")/1024/1024 as \"total\", last(\"Active\")/1024/1024 as \"active\", last(\"MemFree\")/1024/1024 as \"free\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  { "title": "Netinfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "pktMon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "$tag_status",
     "query": "SELECT \"count\" FROM \"pkt_staus\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"status\""
    }
   ]
  },
  {
   "title": "pktMon logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT \"logs\" FROM \"pkt_log\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "pingtrace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "l_rx_kern",
     "query": "SELECT \"l_rx_kern\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_rx_merged_kern",
     "query": "SELECT \"l_rx_merged_kern\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_rx_task_waking",
     "query": "SELECT \"l_rx_task_waking\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_tx_kern",
     "query": "SELECT \"l_tx_kern\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_tx_merged_kern",
     "query": "SELECT \"l_tx_merged_kern\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_tx_qdisc",
     "query": "SELECT \"l_tx_qdisc\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "l_rx_task_queue",
     "query": "SELECT \"l_rx_task_queue\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "total",
     "query": "SELECT \"total\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "tcp connect retrans",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "query": "SELECT \"log\" FROM \"syn_retrans\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "socket count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "FRAG",
     "query": "SELECT \"FRAG\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "INET",
     "query": "SELECT \"INET\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "RAW",
     "query": "SELECT \"RAW\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "UDP",
     "query": "SELECT \"UDP\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "TCP",
     "query": "SELECT \"tcp\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "tcp status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "closed",
     "query": "SELECT \"tcp_closed\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "estab",
     "query": "SELECT \"tcp_estab\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "orphaned",
     "query": "SELECT \"tcp_orphaned\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "synrecv",
     "query": "SELECT \"tcp_synrecv\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "timewait",
     "query": "SELECT \"tcp_timewait\" FROM \"socket\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "runlatency log nums",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "log_counts",
     "query": "SELECT \"count\" FROM \"net_log_c\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "tcp_reset",
     "query": "SELECT \"count\" FROM \"net_reset_c\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "tcp_retrans",
     "query": "SELECT \"count\" FROM \"net_retrans_c\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "runlatency logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 32 },
   "targets": [
    {
     "query": "SELECT \"log\" FROM \"net_log\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "tcp_reset logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"log\" FROM \"net_reset\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "net_retrans logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "query": "SELECT \"log\" FROM \"net_retrans\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  { "title": "Sched", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "CPU - Utilisation for Total System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "alias": "User",
     "query": "SELECT mean(\"user\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "System",
     "query": "SELECT mean(\"sys\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Steal",
     "query": "SELECT mean(\"steal\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "SoftIRQ",
     "query": "SELECT mean(\"softirq\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "HardIRQ",
     "query": "SELECT mean(\"hardirq\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Nice",
     "query": "SELECT mean(\"nice\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "IOwait",
     "query": "SELECT mean(\"iowait\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Guest",
     "query": "SELECT mean(\"guest\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "GuestNice",
     "query": "SELECT mean(\"guestnice\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Run Queue & Blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "alias": "Running",
     "query": "SELECT mean(\"procs_running\") FROM \"stat_counters\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Blocked",
     "query": "SELECT mean(\"procs_blocked\") FROM \"stat_counters\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "per cpu user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "query": "SELECT \"user\" FROM \"cpus\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"cpu_name\""
    }
   ]
  },
  {
   "title": "per cpu sys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "query": "SELECT \"sys\" FROM \"cpus\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"cpu_name\""
    }
   ]
  },
  {
   "title": "per cpu softirq",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "query": "SELECT \"softirq\" FROM \"cpus\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"cpu_name\""
    }
   ]
  },
  {
   "title": "per cpu iowait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "query": "SELECT \"iowait\" FROM \"cpus\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"cpu_name\""
    }
   ]
  },
  {
   "title": "Process fork()",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "alias": "fork",
     "query": "SELECT mean(\"processes_forks\") FROM \"stat_counters\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Process Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "targets": [
    {
     "alias": "ctxt",
     "query": "SELECT mean(\"ctxt\") FROM \"stat_counters\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Memory Available/Free",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Available",
     "query": "SELECT last(\"MemAvailable\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Free",
     "query": "SELECT last(\"MemFree\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Memory Active/InActive",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Active",
     "query": "SELECT last(\"Active\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Inactive",
     "query": "SELECT last(\"Inactive\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Active\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "InActive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Inactive\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "InActive_anon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Inactive_anon\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Active_anon",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Active_anon\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Active_file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Active_file\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "InActive_file",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Inactive_file\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Buffers",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Buffers\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Cached\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "CommitLimit",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"CommitLimit\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Dirty",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Dirty\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "KernelStack",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"KernelStack\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Mapped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"Mapped\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MemAvailable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"MemAvailable\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MemFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"MemFree\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MemTotal",
     "query": "SELECT \"MemTotal\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "PageTables",
     "query": "SELECT \"PageTables\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "Memory Total & Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "MemTotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"MemTotal\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MemFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"MemFree\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "MemAvailable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"MemAvailable\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory Active & Inactive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Active\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "InActive",
     "query": "SELECT mean(\"Inactive\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Paging Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"SwapTotal\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Free",
     "query": "SELECT mean(\"SwapFree\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Cached",
     "query": "SELECT mean(\"SwapCached\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Paging Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "Paging_page_in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pgpgin\") FROM \"proc_vmstat\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Paging_page_out",
     "query": "SELECT mean(\"pgpgout\") FROM \"proc_vmstat\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Paging_swap_in",
     "query": "SELECT mean(\"pswpin\") FROM \"proc_vmstat\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Paging_swap_out",
     "query": "SELECT mean(\"pswpout\") FROM \"proc_vmstat\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Disks KB/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rkb\" FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "query": "SELECT \"wkb\" *  -1 FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\""
    },
    {
     "alias": "Cached",
     "query": "SELECT mean(\"SwapCached\") FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Disks Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"reads\" FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "query": "SELECT \"writes\" *  -1 FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\""
    }
   ]
  },
  {
   "title": "Disks Busy Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_disk_name]].Busy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"busy\" FROM \"disks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "disk wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[tag_disk_name]]_r",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rwait\" FROM \"disk_wait\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_disk_name]]_w",
     "query": "SELECT \"wwait\"  *-1 FROM \"disk_wait\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"disk_name\""
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "Network Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "[[tag_network_name]].ibytes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ibytes\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_network_name]].obytes",
     "query": "SELECT \"obytes\" *  -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_network_name]].ipackets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ipackets\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_network_name]].opackets",
     "query": "SELECT \"opackets\" *  -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_network_name]].idropped",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"idrop\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_network_name]].odropped",
     "query": "SELECT \"odrop\" *  -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].ierrs",
     "query": "SELECT \"ierrs\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].oerrs",
     "query": "SELECT \"oerrs\" *  -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].ioverruns",
     "query": "SELECT \"ififo\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].ooverruns",
     "query": "SELECT \"ofifo\" *  -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "[[tag_network_name]].iframe",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"iframe\" FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "[[tag_network_name]].ocarrier",
     "query": "SELECT \"ocarrier\"  * -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].ocolls",
     "query": "SELECT \"ocolls\"  * -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    },
    {
     "alias": "[[tag_network_name]].ocolls",
     "query": "SELECT \"ocolls\"  * -1 FROM \"networks\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter GROUP BY \"network_name\""
    }
   ]
  },
  { "title": "Dist", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 } },
  {
   "title": "cpudist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "us1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"us1\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "us10",
     "query": "SELECT \"us10\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "us100",
     "query": "SELECT \"us100\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "ms1",
     "query": "SELECT \"ms1\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "ms10",
     "query": "SELECT \"ms10\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "ms100",
     "query": "SELECT \"ms100\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "s1",
     "query": "SELECT \"s1\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "so",
     "query": "SELECT \"so\" FROM \"cpudist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "loghealth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "hung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hung\" FROM \"loghealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "io",
     "query": "SELECT \"io\" FROM \"loghealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "mem",
     "query": "SELECT \"mem\" FROM \"loghealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "net",
     "query": "SELECT \"net\" FROM \"loghealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "wait",
     "query": "SELECT \"wait\" FROM \"loghealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "hungs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hungs\" FROM \"health\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ios",
     "query": "SELECT \"ios\" FROM \"health\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "mems",
     "query": "SELECT \"mems\" FROM \"health\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "waits",
     "query": "SELECT \"waits\" FROM \"health\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "nets",
     "query": "SELECT \"nets\" FROM \"health\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "perhealth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "hung",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"hung\" FROM \"perhealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "io",
     "query": "SELECT \"io\" FROM \"perhealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "net",
     "query": "SELECT \"net\" FROM \"perhealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "mem",
     "query": "SELECT \"mem\" FROM \"perhealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "wait",
     "query": "SELECT \"wait\" FROM \"perhealth\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  },
  {
   "title": "virtout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "ms100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ms100\" FROM \"virthist\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "so",
     "query": "SELECT \"so\" FROM \"virthist\" WHERE $timeFilter"
    },
    {
     "alias": "s1",
     "query": "SELECT \"s1\" FROM \"virthist\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "nethist",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "ms10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"ms10\" FROM \"net_hist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "ms100",
     "query": "SELECT \"ms100\" FROM \"net_hist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "s1",
     "query": "SELECT \"s1\" FROM \"net_hist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    },
    {
     "alias": "so",
     "query": "SELECT \"so\" FROM \"net_hist\" WHERE (\"host\" =~ /^$LINUXHOST$/) AND $timeFilter"
    }
   ]
  }
 ]
}