{
 "title": "netMonRemote",
 "description": "longcheer data gathers for Linux on any platform: AMD64, POWER8/9, Raspberry Pi and any Linux versionIncludes 14 graphs of the regular CPU, memory, disks, filesystems and networks plus memory Pie charts and table view of memory extra stats.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   { "name": "DS_INFLUXDB", "label": "database", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "sumary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "LINUXHOST" },
  {
   "title": "cluster info",
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "content": "this is a vm\n" },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operating System",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "os_release",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Operating System Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "os_release",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "version_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Architecture",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "architecture" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU health",
   "type": "stat",
   "description": "CPU health，should not lower than 60%",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "identity",
     "query": "select floor(mean(idle)) from cpu_total where  (\"host\" =~ /^$node$/) and time > now() - 10m",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "disk busy rate(%)",
   "type": "stat",
   "description": "disk busy rate. the lower the better",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "identity",
     "query": "select max(busy) from disks where (\"host\" =~ /^$node$/) and time > now() - 10m",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "mem summary",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(\"MemTotal\")/1024/1024 as \"total\", last(\"Active\")/1024/1024 as \"active\", last(\"MemFree\")/1024/1024 as \"free\" FROM \"proc_meminfo\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Threads per core",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "threads_per_core" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Logical CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "net retrans",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "identity",
     "query": "select sum(total) as retrans from net_retrans where (\"host\" =~ /^$node$/) and time > now() - 1h",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "identity",
     "query": "SELECT last(\"model\") FROM \"identity\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "model" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Model Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT last(\"architecture\") FROM \"lscpu\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "model_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Processors Vendor (not on all systems)",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "measurement": "lscpu",
     "query": "SELECT \"name\" +  \"version\" FROM \"os_release\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "vendor_id" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "netinfo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "LINUXHOST" },
  {
   "title": "pktMon",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_status",
     "groupBy": [
      { "params": [ "status" ], "type": "tag" }
     ],
     "measurement": "pkt_staus",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "pktMon Iogs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "measurement": "pkt_log",
     "select": [
      [
       { "params": [ "logs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "pingtrace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "l_rx_kern",
     "measurement": "pingtrace",
     "query": "SELECT \"l_rx_kern\" FROM \"pingtrace\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter GROUP BY \"/^$node$/\"",
     "select": [
      [
       { "params": [ "l_rx_kern" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_rx_merged_kern",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "l_rx_merged_kern" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_rx_task_waking",
     "measurement": "pingtrace",
     "query": "SELECT \"l_rx_task_queue\" FROM \"pingtrace\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "l_rx_task_waking" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_tx_kern",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "l_tx_kern" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_tx_merged_kern",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "l_tx_merged_kern" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_tx_qdisc",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "l_tx_qdisc" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "l_rx_task_queue",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "l_rx_task_queue" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "total",
     "measurement": "pingtrace",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "tcp retrans total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "measurement": "net_retrans",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "retrans logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "measurement": "net_retrans_log",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "socket count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "FRAG",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "FRAG" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "INET",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "INET" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "RAW",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "RAW" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "UDP",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "UDP" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "TCP",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "tcp status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "closed",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp_closed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "estab",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp_estab" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "orphaned",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp_orphaned" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "synrecv",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp_synrecv" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "timewait",
     "measurement": "socket",
     "select": [
      [
       { "params": [ "tcp_timewait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "log counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "runlat_log_counts",
     "measurement": "net_log_c",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "tcp_reset",
     "measurement": "net_reset_c",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "tcp_retrans",
     "measurement": "net_retrans_c",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "runlatency logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 32 },
   "targets": [
    {
     "measurement": "net_log",
     "query": "SELECT \"log\" FROM \"net_log\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "tcp_reset logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "measurement": "net_log",
     "query": "SELECT \"log\" FROM \"net_reset\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "net_retrans logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "measurement": "net_log",
     "query": "SELECT \"log\" FROM \"net_retrans\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "log" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "sched", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 }, "repeat": "LINUXHOST" },
  {
   "title": "CPU - Utilisation for Total System",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "query": "SELECT mean(\"user\") FROM \"cpu_total\" WHERE (\"host\" =~ /^$node$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "System",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Steal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "steal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "SoftIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "HardIRQ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "hardirq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Nice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "nice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "IOwait",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Guest",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "guest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "GuestNice",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu_total",
     "select": [
      [
       { "params": [ "guestnice" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Run Queue & Blocked",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "procs_running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "procs_blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "per cpu user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "per cpu sys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "sys" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "per cpu softirq",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "softirq" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "per cpu iowait",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "cpu_name" ], "type": "tag" }
     ],
     "measurement": "cpus",
     "select": [
      [
       { "params": [ "iowait" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Process fork()",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "fork",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "processes_forks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Process Context Switches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "ctxt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stat_counters",
     "select": [
      [
       { "params": [ "ctxt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 }, "repeat": "LINUXHOST" },
  {
   "title": "Memory Available/Free",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 82 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Available",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Active/InActive",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 82 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Inactive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "InActive",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "InActive_anon",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive_anon" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Active_anon",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active_anon" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Active_file",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active_file" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "InActive_file",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive_file" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Buffers",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Buffers" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Cached",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Cached" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "CommitLimit",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "CommitLimit" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Dirty",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Dirty" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "KernelStack",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "KernelStack" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Mapped",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Mapped" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "MemAvailable",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "MemFree",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "MemTotal",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemTotal" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "PageTables",
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "PageTables" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Total & Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "MemTotal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "MemFree",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "MemAvailable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "MemAvailable" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Active & Inactive",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Active" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "InActive",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "Inactive" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Paging Space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "SwapTotal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Free",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "SwapFree" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Cached",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_meminfo",
     "select": [
      [
       { "params": [ "SwapCached" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Paging Rates",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Paging_page_in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pgpgin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Paging_page_out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pgpgout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Paging_swap_in",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pswpin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "Paging_swap_out",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "proc_vmstat",
     "select": [
      [
       { "params": [ "pswpout" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 106 } },
  {
   "title": "Disks KB/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "rkb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "wkb" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disks Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Read",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "reads" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_disk_name]].Write",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "writes" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Disks Busy Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_disk_name]].Busy",
     "groupBy": [
      { "params": [ "disk_name" ], "type": "tag" }
     ],
     "measurement": "disks",
     "select": [
      [
       { "params": [ "busy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "File Systems Free space",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_filesystem_name]]",
     "groupBy": [
      { "params": [ "filesystem_name" ], "type": "tag" }
     ],
     "measurement": "filesystems",
     "select": [
      [
       { "params": [ "fs_free_mb" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }, "repeat": "LINUXHOST" },
  {
   "title": "Network Bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].ibytes",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ibytes" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].obytes",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "obytes" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Packets",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].ipackets",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ipackets" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].opackets",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "opackets" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].idropped",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "idrop" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].odropped",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "odrop" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ierrs",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ierrs" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].oerrs",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "oerrs" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ioverruns",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ififo" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ooverruns",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ofifo" ], "type": "field" },
       { "params": [ "*  -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Drops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_network_name]].iframe",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "iframe" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ocarrier",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ocarrier" ], "type": "field" },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ocolls",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ocolls" ], "type": "field" },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    },
    {
     "alias": "[[tag_network_name]].ocolls",
     "groupBy": [
      { "params": [ "network_name" ], "type": "tag" }
     ],
     "measurement": "networks",
     "select": [
      [
       { "params": [ "ocolls" ], "type": "field" },
       { "params": [ " * -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  { "title": "interrupt", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 }, "repeat": "LINUXHOST" },
  {
   "title": "interrupts by cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "interrupts_c_name" ], "type": "tag" }
     ],
     "measurement": "interrupts_c",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  },
  {
   "title": "interrupts by irq",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "interrupts_i_name" ], "type": "tag" }
     ],
     "measurement": "interrupts_i",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$node$/" }
     ]
    }
   ]
  }
 ]
}