# Generated by Django 3.2.8 on 2022-11-28 06:49

from django.db import migrations, models
import lib.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='创建时间')),
                ('updated_at', models.CharField(default=lib.utils.human_datetime, max_length=20, verbose_name='更新时间')),
                ('task_id', models.CharField(default='', max_length=64, verbose_name='任务实例ID')),
                ('status', models.CharField(choices=[('Ready', 'Ready'), ('Running', 'Running'), ('Success', 'Success'), ('Fail', 'Fail')], default='Ready', max_length=32, verbose_name='任务状态')),
                ('command', models.TextField(verbose_name='shell文本')),
                ('result', models.JSONField(default=dict, verbose_name='shell结果')),
                ('params', models.JSONField(default=dict, verbose_name='params')),
                ('host_by', models.TextField(default='', max_length=64, verbose_name='host_jobs')),
                ('created_by', models.IntegerField(verbose_name='创建人')),
            ],
            options={
                'db_table': 'sys_job',
            },
        ),
    ]
